name: Combined Workflows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      # Define the output variable to capture secret scanning results
      id: secret_scanning_output
      value: ${{ steps.secret_scanning.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        id: secret_scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

  slackNotification:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.outputs.secret_scanning_output != '{"verified_secrets":0}' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # Pass the secret scanning result as an environment variable
          SLACK_MESSAGE: ${{ needs.test.outputs.secret_scanning_output }}
